"use client";
import "./globals.css";
import Provider from "./provider";
import localFont from "next/font/local";

const BeVietnamPro = localFont({
  src: [
    {
      path: "../../public/fonts/BeVietnamPro-Regular.ttf",
      weight: "400",
    },
    {
      path: "../../public/fonts/BeVietnamPro-Medium.ttf",
      weight: "500",
    },
    {
      path: "../../public/fonts/BeVietnamPro-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "../../public/fonts/BeVietnamPro-Bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-be-vn",
});
export const metadata = {
  title: "quiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${BeVietnamPro.variable} font-bevn`}>
          <Provider>{children}</Provider>
      </body>
    </html>
  );
}
