"use client";
import "./antd.css";
import "./globals.css";
import 'antd/dist/reset.css';
import Provider from "./provider";
import { ConfigProvider } from "antd";
import localFont from "next/font/local";

const BeVietnamPro = localFont({
  src: [
    {
      path: "../../public/fonts/BeVietnamPro-Regular.ttf",
      weight: "400",
    },
    {
      path: "../../public/fonts/BeVietnamPro-Medium.ttf",
      weight: "500",
    },
    {
      path: "../../public/fonts/BeVietnamPro-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "../../public/fonts/BeVietnamPro-Bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-be-vn",
});
export const metadata = {
  title: "Mobifone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${BeVietnamPro.variable} font-bevn`}>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#0060AF",
              fontFamily: BeVietnamPro.style.fontFamily,
            },
          }}
        >
          <Provider>{children}</Provider>
        </ConfigProvider>
      </body>
    </html>
  );
}
